apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-web
  template:
    metadata:
      labels:
        app: zabbix-web
    spec:
      containers:
      - name: zabbix-web
        image: zabbix/zabbix-web-nginx-mysql:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_SERVER_HOST
          value: "my-mysql"
        - name: MYSQL_USER
          value: "zabbix"
        - name: MYSQL_PASSWORD
          value: "zabbix_password"
        - name: MYSQL_DATABASE
          value: "zabbix"
        - name: MYSQL_ROOT_PASSWORD
          value: "root_password"
